### PR TITLE
sf for shapes and stops

### LINKED ISSUE #115: create shapes_sf if available

### PR DESCRIPTION
**Pull request by polettif**
Closes #115. With this PR the only sf data frames calculated by tidytransit are stops and shapes. As mentioned in #108 shapes are connected to one or more trips which are then connected to routes. Which means we can join route shapes (in `get_route_geometry`) "on the fly".

- `gtfs_as_sf` only converts stops and shapes and replaces those tables in gtfs_obj. IMHO there's generally no point in keeping shapes in its csv format as practically no information is lost by conversion. The stops sf data frame is generally the same just with a geometry column added.  
- renamed `get_stop_geometry` to `stops_as_sf` (like `gtfs_as_sf` and the new `shapes_as_sf`)
- `get_route_geometry` needs a gtfs_obj with shapes as sf
- renamed (and updated) the example data set gtfs_obj to gtfs_duke to avoid confusion
- Added some utility functions and updated messages

### CODE REVIEW

**Comment by tbuckl** [comment]
@polettif in case you hadn't seen, heads up that the frequency vignette renders the last 2 plots blank on this PR. i think its the buffered routes. can check it out this weekend.

**Comment by tbuckl** [comment]
@polettif thanks for all the awesome work here! i'm excited about all the functionality this opens up. its a much better way to handle the shapes. 

the last 2 plots on the frequency vignette broke because they were based on a CRS in which units were in decimal degrees. by changing the CRS, you effectively changed the denominator on the cartogram (from decimal degrees to meters). 

there are two options for fixing them, one of which is pushed to this branch. they are:

1. (on this branch/PR) - don't use a projected crs. its always great to 'use the right crs'. but the right CRS depends on your purposes. here, a projected crs improved the cartographic accuracy. but these plots of the subway are closer to graphics than to maps, so there's a case to be made that 4326 is fine, especially for some reasons listed below. 

2. (on [this other branch/PR](https://github.com/r-transit/tidytransit/pull/125)) using the projected CRS, adjust the units for the cartograms in the last 2 plots so that they work again. this results in some nice maps too. unfortunately, ggplot's alpha seems to be broken on geom_sf projected coordinate systems. so you don't get that layering effect that you get in (1). 

anyway, i'm fine with either of these because they both look great. could perhaps combine them in one vignette if thats preferable.

**Comment by tbuckl** [comment]
@polettif nevermind looks like all that might be required is a change in the use of ggplot. will post update today.

**Comment by tbuckl** [comment]
@polettif After a bit of digging around, the map is not rendering as it was before because of how `get_route_geometry` works in this PR. 

`get_route_geometry` in this PR returns ~7k rows/routes, many of them identical.

i understand why you want to build `get_route_geometry` on top of `get_trip_geometry`, but as it is implemented right now, i'm not sure it will make sense to users. 

when i want `routes` as a user, i would expect some kind of table that is very similar to the routes table in gtfs, with a similar number of units. so if there are 30 routes, i'd expect 30 routes returned by a function that `gets_routes`. or, at the very least, i'd like an optional flag to allow me to get 30 routes if i want, or 7k of them if there are indeed 7k unique versions of the routes. 

in this case, i don't think there are 7k unique versions of the route. i think `get_route_geometry` is actually just returning something like `trip_geometry`

**Comment by polettif** [comment]
Thanks a lot for looking into it! To be honest, I wasnt quite sure, what `get_route_geometry` is supposed to do (I guess another reason to add tests). You're right, as it stands it really doesn't do the same as before, didn't catch that.
> when i want routes as a user, i would expect some kind of table that is very similar to the routes table in gtfs, with a similar number of units. so if there are 30 routes, i'd expect 30 routes returned by a function that gets_routes. or, at the very least, i'd like an optional flag to allow me to get 30 routes if i want, or 7k of them if there are indeed 7k uniquely traversed geometries of the routes.


Which means one multilinestring per route, right? I think I can change this PR accordingly (using `summarise` or something like that with sf) because I'd really like to move on from calculating all routes again (as you propose in #126).

**Comment by tbuckl** [comment]
@polettif ah, sorry. i clearly did not document the `get_routes_geometry` function well enough. i can work on that next weekend. ill be sure to check on your branches before i do any work to see where you're going with it first.

**Comment by tbuckl** [comment]
@polettif and to answer your multilinestring question very broadly: the goal originally, for some work for the state legislature in california, was to define service quality along a "transit corridor." the end user in that case is a legislator that is trying to decide how to plan transit, housing, and employment. i don't want to be narrow minded about what a "route" or "corridor" is. it could be a multiinestring, or if that specification doesn't work (for example, because the route loops in a weird way, or traverses multiple shapes in a weird way), then it might have to be a polygon. in any case, i think the solution as it is now, for returning as many single geometries for routes as there are routes on the gtfs routes table, has a use case, which is tied to a state of california legislative process. is there a compelling reason (ideally a user problem that trumps this one) to throw that out? if so, i haven't really heard it.

**Comment by tbuckl** [comment]
@polettif it could be that we rename the current function `get_corridor_geometry` or something like that. and then `get_route_geometry` is the function you are proposing here.

**Comment by polettif** [comment]
`get_route_geometry` really didn't work as I intended originally, returning that many shapes was a bug. It should be fixed with the latest commits. The function now returns one row/shape per route_id. As far as I can tell it's the same result as before but slightly faster ().

> the goal of the route geometry function was to represent high quality transit corridors [for the state legislature in california](https://sf.curbed.com/2019/5/10/18563360/senate-bill-50-chart-sb50-explainer-housing-transit). it was hoped that the end user in that case is a legislator that is trying to decide how to plan transit, housing, and employment.
Very interesting! I don't really have another use case, so there's no need to change `get_route_geometry`'s behavior. Just out of curiosity: Isn't using buffered routes as a corridor to indicate "transit quality" a bit misleading if stops are far apart?

**Comment by polettif** [comment]
@tbuckl Any objection if I merge this?

**Comment by tbuckl** [comment]
@polettif no objections! seems great!

**Pull request merged**
