### PR TITLE
remove zip extension check-this can be made explicit in docs

### PR DESCRIPTION
**Pull request by polettif**
Less of a PR, more of a design question: Should reading a feed directly from a local directory be possible or not? I know, a gtfs feed is only complete if it's a zip file but we extract every file anyways. For me at least it's useful to read a local feed from a directory after I've changed some stuff, so zipping (and unzipping) is a bit of a nuisance.

### CODE REVIEW

**Comment by tbuckl** [comment]
@polettif thats an interesting question. 

i was wondering if having a more generic r package where you could read_csv() on a directory, with a specification.  

if we abstracted that kind of functionality out we could easily import it here in this package, but i could see it being useful in other circumstances as well. 

i once used (begrudgingly at first) a "pipeline orchestration tool" that allowed users to specify csv's in pandas read_csv code and then have it evaluated in a lazy way. its called [orca](https://github.com/UDST/orca). 

i imagine that pandas/python has this more figured out, but i saw that people just suggest writing python to handle [situations like this](https://stackoverflow.com/questions/20906474/import-multiple-csv-files-into-pandas-and-concatenate-into-one-dataframe).

for GTFS, i can't imagine a circumstance in which I would want to actually edit specified feed files. but i'm mainly an analyst.

i imagine that [conveyal](https://github.com/conveyal) must have thought about this re:editing.

**Comment by polettif** [comment]
Good points. A more generic read_csv_directory package could be useful but I think the overhead is not needed for tidytransit and IMHO time is better spent on other issues. I haven't worked with python at all, so I can't really touch on the approaches you mentioned. 

So I'd say you need to provide a zip file to read_gtfs for it to work. More straightforward and we don't add more flags and options.

**Comment by polettif** [comment]
I added a commit to remove the zip extension condition which shouldn't be necessary.

**Comment by tbuckl** [comment]
sounds good, thanks again @polettif

**Pull request merged**
