### PR TITLE
Switch from lubridate to hms (2)

### PR DESCRIPTION
**Pull request by polettif**
Resubmitting #28 because I can't find the merge commit on the master branch. Don't really know what happened, I might have been to loose with deleting and merging recently. @tbuckl is it possible it got lost on the route-type-branch?

### CODE REVIEW

**Comment by tbuckl** [comment]
hi @polettif, i checked through the commit for a file that was changed in #26 (r/time.R) and saw that it was not reverted in the route-type branch but it was also never fully merged. 

while i can't remember exactly what happened with that commit, i do recall that i might have cherry-picked commits or lines that seemed more functional or passed tests or were documented. 

while i can't take a hard look at this again until this weekend, if you need this PR in the package, i'd say go for it, but just make sure it passes tests. 

note that i slimmed down some of the test environments, so the tests are slightly less robust than they used to be. but travis/r was giving me difficulty with an os x env that i did not have time to debug.

**Comment by tbuckl** [comment]
oh wait, no #26 was fully merged. this new PR (#38) contains at least one line, the one linked above, that was not in #26. 

anyway, i can take a look this weekend if you want a review. or go ahead and merge pending passing checks.

**Comment by tbuckl** [comment]
@polettif hang on i got the PR's confused. let me check a bit more.

**Comment by tbuckl** [comment]
@polettif weird, i'm very sorry about that. looks like that commit did disappear!

**Comment by polettif** [comment]
> do you have a pressing need for these changes to be reflected in CRAN 3.5 or can you pull them from CRAN 3.4?
No need. To be honest, I don't really know how CRAN releases work anyways. I normally install the github development version.

**Pull request merged**
