### PR TITLE
restore get_route_frequency and vignette

### LINKED ISSUE #166: add get_route_frequency() and document deprecation
Function get_route_frequency() was available in 0.7.3, but I'm not seeing it in 1.0.0.

### PR DESCRIPTION
**Pull request by polettif**
This PR restores get_route_frequency() and the frequence & headways vignette. However, some changes have been made to `get_route_frequency` and `get_stop_frequency`:
- `start_time` and `end_time` are in seconds (instead of hours, now works like `filter_stop_times`)
- dow (day of week) parameter was removed, service selection works via service_id, as explained in the vignette
- headways are now returned in seconds

`filter_stop_times` now does not need a start or end time and can be used to filter a feed only by a date.

@tbuckl I'm sorry your well thought out and illustrative vignette has been missing from the package. I took the liberty to update some code in the vignette, its core hasn't changed though.

Closes #166

### CODE REVIEW

**Comment by tbuckl** [comment]
awesome--love to see that vignette back--i've wondered if that vignette might actually be better as "blog post" or something rather than a vignette. i did notice that, as it is now, the headways are way off. could just be that nyc service_id's are funky.

**Comment by polettif** [comment]
> i've wondered if that vignette might actually be better as "blog post" or something rather than a vignette.

That's a good point, I've been tinkering with a vignette for Swiss "public transit quality areas" but now that you mention it, a blog post might be indeed better for things like that. I wouldn't know where to put it though.

> i did notice that, as it is now, the headways are way off. could just be that nyc service_id's are funky.

Hm, that's possible, I haven't looked at the values too closely. Weird service_ids wouldn't be anything new though... Do you have a specific example or is it just an overall observation?

**Comment by tbuckl** [comment]
> > i've wondered if that vignette might actually be better as "blog post" or something rather than a vignette.
> 
> That's a good point, I've been tinkering with a vignette for Swiss "public transit quality areas" but now that you mention it, a blog post might be indeed better for things like that. I wouldn't know where to put it though.

We can maybe think about that as another repo, maybe rendered with bookdown. 

> 
> > i did notice that, as it is now, the headways are way off. could just be that nyc service_id's are funky.
> 
> Hm, that's possible, I haven't looked at the values too closely. Weird service_ids wouldn't be anything new though... Do you have a specific example or is it just an overall observation?

Yeah the values [here](https://tidytransit.r-transit.org/articles/frequency.html#calculate-headways) are way off. Median headways of 480 mins for the NYC metro on a busy schedule can't be correct! 

I had previously just eyeballed that number against a standard NYC schedule. I'm going to open an issue to just flag this for people in case they are relying on methods in that vignette.

**Comment by tbuckl** [comment]
nevermind i misunderstood! you changed what was minutes to seconds--good call and my mistake.

**Pull request merged**
