### PR TITLE
a start at https://github.com/r-transit/tidytransit/issues/108

### PR DESCRIPTION
**Pull request by tbuckl**
rewrote the introduction vignette and frequencies vignette to reflect the plan to deprecate frequency flag in read_gtfs

### CODE REVIEW

**Comment by tbuckl** [comment]
closes #122 #108 and #116

**Comment by tbuckl** [comment]
@polettif i made changes as planned. i hope its what you were expecting! in any case, thanks for the nudge to work on the frequency vignette. there's probably a lot more to be done there.

**Comment by polettif** [comment]
That's great, thank you! Nice work on the frequency vignette, the new plots help a lot.

**Comment by tbuckl** [comment]
@polettif the service selection vignette made it a lot easier to figure out how to make those plots for NYC. many of the GTFS data i've worked with before have simpler schedules.

**Pull request merged**
